# constants.py
ISSUES_LIST = [
    "Treaty on the Prohibition of Nuclear Weapons",
    "Quantitative and qualitative expansion of nuclear arsenals",
    "Humanitarian consequences of nuclear weapon use",
    "Transparency and accountability of nuclear arsenals and doctrines",
    "Role and significance of nuclear weapons in military and security concepts, doctrines and policies",
    "Arms control agreements",
    "Disarmament verification",
    "Reduced role and operational readiness of nuclear weapons",
    "Fulfillment of Article VI disarmament obligations",
    "Security assurances",
    "No first use",
    "Risk reduction and confidence-building measures",
    "Comprehensive Nuclear-Test-Ban Treaty",
    "Moratorium on nuclear testing",
    "The Fissile Material Cutoff Treaty",
    "Moratorium on fissile material production",
    "Legacy of nuclear weapons, their use and testing",
    "Gender",
    "Emerging and disruptive technologies",
    "Nonproliferation and disarmament education",
    "Middle East Weapons of Mass Destruction Free Zone and Israel",
    "Universality of the Treaty on the Non-Proliferation of Nuclear Weapons",
    "Nuclear-Weapon-Free Zones",
    "International Atomic Energy Agency safeguards",
    "Export controls",
    "Regional proliferation challenges including the the Democratic People's Republic of Korea, Iran and Joint Comprehensive Plan of Action",
    "Nuclear threats",
    "Attacks on nuclear facilities",
    "Peaceful uses of nuclear technology",
    "Nuclear safety",
    "Nuclear security",
    "Strengthening the Treaty on the Non-Proliferation of Nuclear Weapons review process",
    "Discouraging the Treaty on the Non-Proliferation of Nuclear Weapons withdrawal",
    "Naval propulsion",
    "Nuclear sharing and extended deterrence",
    "Ukraine"
]
